// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: alliance/alliance/unbonding.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// UnbondingDelegation defines an unbonding object with relevant metadata.
type UnbondingDelegation struct {
	// completion_time is the unix time for unbonding completion.
	CompletionTime time.Time `protobuf:"bytes,1,opt,name=completion_time,json=completionTime,proto3,stdtime" json:"completion_time"`
	// validator_address is the bech32-encoded address of the validator.
	ValidatorAddress string `protobuf:"bytes,2,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	// amount defines the tokens to receive at completion.
	Amount github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,3,opt,name=amount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"amount"`
}

func (m *UnbondingDelegation) Reset()         { *m = UnbondingDelegation{} }
func (m *UnbondingDelegation) String() string { return proto.CompactTextString(m) }
func (*UnbondingDelegation) ProtoMessage()    {}
func (*UnbondingDelegation) Descriptor() ([]byte, []int) {
	return fileDescriptor_09730fb8395606a9, []int{0}
}
func (m *UnbondingDelegation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UnbondingDelegation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UnbondingDelegation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UnbondingDelegation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbondingDelegation.Merge(m, src)
}
func (m *UnbondingDelegation) XXX_Size() int {
	return m.Size()
}
func (m *UnbondingDelegation) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbondingDelegation.DiscardUnknown(m)
}

var xxx_messageInfo_UnbondingDelegation proto.InternalMessageInfo

func (m *UnbondingDelegation) GetCompletionTime() time.Time {
	if m != nil {
		return m.CompletionTime
	}
	return time.Time{}
}

func (m *UnbondingDelegation) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*UnbondingDelegation)(nil), "alliance.alliance.UnbondingDelegation")
}

func init() { proto.RegisterFile("alliance/alliance/unbonding.proto", fileDescriptor_09730fb8395606a9) }

var fileDescriptor_09730fb8395606a9 = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xb1, 0x4e, 0xeb, 0x30,
	0x14, 0x86, 0xe3, 0xde, 0xab, 0xea, 0xde, 0x5c, 0xe9, 0x42, 0x43, 0x87, 0xd0, 0x21, 0x29, 0x0c,
	0xa8, 0x4b, 0x12, 0x04, 0x1b, 0x62, 0xa1, 0x82, 0xa1, 0x48, 0x2c, 0xa5, 0x2c, 0x2c, 0x95, 0x93,
	0x18, 0x13, 0x91, 0xf8, 0x44, 0xb6, 0x83, 0xe8, 0x13, 0xb0, 0xf6, 0x11, 0x78, 0x88, 0x3e, 0x44,
	0xc7, 0xaa, 0x13, 0x62, 0x28, 0xa8, 0x5d, 0x78, 0x0c, 0x94, 0xc4, 0x69, 0x11, 0x53, 0xfe, 0x93,
	0xef, 0xfc, 0xff, 0xb1, 0x8f, 0xf5, 0x3d, 0x1c, 0xc7, 0x11, 0x66, 0x01, 0xf1, 0xd6, 0x22, 0x63,
	0x3e, 0xb0, 0x30, 0x62, 0xd4, 0x4d, 0x39, 0x48, 0x30, 0x1a, 0x15, 0x71, 0x2b, 0xd1, 0x6a, 0x52,
	0xa0, 0x50, 0x50, 0x2f, 0x57, 0x65, 0x63, 0x6b, 0x37, 0x00, 0x91, 0x80, 0x18, 0x96, 0xa0, 0x2c,
	0x14, 0xb2, 0x28, 0x00, 0x8d, 0x89, 0x57, 0x54, 0x7e, 0x76, 0xe7, 0x85, 0x19, 0xc7, 0x32, 0x02,
	0xa6, 0xb8, 0xfd, 0x93, 0xcb, 0x28, 0x21, 0x42, 0xe2, 0x24, 0x2d, 0x1b, 0xf6, 0x9f, 0x6b, 0xfa,
	0xce, 0x4d, 0x75, 0xb0, 0x73, 0x12, 0x13, 0x5a, 0xd8, 0x8d, 0x2b, 0x7d, 0x2b, 0x80, 0x24, 0x8d,
	0x49, 0x5e, 0x0d, 0x73, 0x97, 0x89, 0xda, 0xa8, 0xf3, 0xef, 0xa8, 0xe5, 0x96, 0x91, 0x6e, 0x15,
	0xe9, 0x0e, 0xaa, 0xc8, 0xee, 0x9f, 0xe9, 0xc2, 0xd6, 0xc6, 0xef, 0x36, 0xea, 0xff, 0xdf, 0x98,
	0x73, 0x6c, 0x5c, 0xe8, 0x8d, 0x47, 0x1c, 0x47, 0x21, 0x96, 0xc0, 0x87, 0x38, 0x0c, 0x39, 0x11,
	0xc2, 0xac, 0xb5, 0x51, 0xe7, 0x6f, 0xd7, 0x9c, 0x4f, 0x9c, 0xa6, 0xba, 0xd4, 0x59, 0x49, 0xae,
	0x25, 0x8f, 0x18, 0xed, 0x6f, 0xaf, 0x2d, 0xea, 0xbf, 0x31, 0xd0, 0xeb, 0x38, 0x81, 0x8c, 0x49,
	0xf3, 0x57, 0xe1, 0x3d, 0xcd, 0x07, 0xbe, 0x2d, 0xec, 0x03, 0x1a, 0xc9, 0xfb, 0xcc, 0x77, 0x03,
	0x48, 0xd4, 0x7e, 0xd4, 0xc7, 0x11, 0xe1, 0x83, 0x27, 0x47, 0x29, 0x11, 0x6e, 0x8f, 0xc9, 0xf9,
	0xc4, 0xd1, 0xd5, 0xa4, 0x1e, 0x93, 0x7d, 0x95, 0x75, 0xf2, 0xfb, 0xf3, 0xc5, 0x46, 0xdd, 0xcb,
	0xe9, 0xd2, 0x42, 0xb3, 0xa5, 0x85, 0x3e, 0x96, 0x16, 0x1a, 0xaf, 0x2c, 0x6d, 0xb6, 0xb2, 0xb4,
	0xd7, 0x95, 0xa5, 0xdd, 0x1e, 0x7e, 0x4b, 0x97, 0x84, 0x73, 0xec, 0x24, 0xc0, 0xc8, 0x68, 0xf3,
	0xb2, 0x4f, 0x1b, 0x59, 0xcc, 0xf2, 0xeb, 0xc5, 0x72, 0x8e, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x1c, 0xd5, 0x9e, 0x40, 0x06, 0x02, 0x00, 0x00,
}

func (this *UnbondingDelegation) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*UnbondingDelegation)
	if !ok {
		that2, ok := that.(UnbondingDelegation)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.CompletionTime.Equal(that1.CompletionTime) {
		return false
	}
	if this.ValidatorAddress != that1.ValidatorAddress {
		return false
	}
	if !this.Amount.Equal(that1.Amount) {
		return false
	}
	return true
}
func (m *UnbondingDelegation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UnbondingDelegation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UnbondingDelegation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintUnbonding(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintUnbonding(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0x12
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.CompletionTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CompletionTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintUnbonding(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintUnbonding(dAtA []byte, offset int, v uint64) int {
	offset -= sovUnbonding(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *UnbondingDelegation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CompletionTime)
	n += 1 + l + sovUnbonding(uint64(l))
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovUnbonding(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovUnbonding(uint64(l))
	return n
}

func sovUnbonding(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozUnbonding(x uint64) (n int) {
	return sovUnbonding(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *UnbondingDelegation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUnbonding
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UnbondingDelegation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UnbondingDelegation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletionTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUnbonding
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUnbonding
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthUnbonding
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.CompletionTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUnbonding
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUnbonding
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUnbonding
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUnbonding
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUnbonding
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUnbonding
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUnbonding(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUnbonding
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipUnbonding(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowUnbonding
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUnbonding
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUnbonding
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthUnbonding
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupUnbonding
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthUnbonding
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthUnbonding        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowUnbonding          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupUnbonding = fmt.Errorf("proto: unexpected end of group")
)
